// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  HomePage: {
    title: 'Salom dunyo!';
    about: 'Go to the about page';
  };
};
export default messages;
